export const SEED_CARS = [
  { name: "Toyota New Vios White", plateNumber: "งพ 7304", type: "Sedan", category: "Car" },
  { name: "Toyota New Vios White", plateNumber: "งร 9614", type: "Sedan", category: "Car" },
  { name: "Toyota New Vios White", plateNumber: "ขว 9053", type: "Sedan", category: "Car" },
  { name: "Toyota New Vios White", plateNumber: "ขว 9047", type: "Sedan", category: "Car" },
  { name: "Toyota New Vios White", plateNumber: "ขอ 6530", type: "Sedan", category: "Car" },
  { name: "Toyota New Vios White", plateNumber: "ขอ 6529", type: "Sedan", category: "Car" },
  { name: "Toyota New Vios White", plateNumber: "งธ 2720", type: "Sedan", category: "Car" },
  { name: "Toyota New Vios White", plateNumber: "งธ 4056", type: "Sedan", category: "Car" },
  { name: "Toyota New Vios White", plateNumber: "งธ 7136", type: "Sedan", category: "Car" },
  { name: "Toyota New Vios White", plateNumber: "จง 5093", type: "Sedan", category: "Car" },
  { name: "Toyota New Vios White", plateNumber: "จง 3345", type: "Sedan", category: "Car" },
  { name: "Toyota New Vios White", plateNumber: "จจ 6447", type: "Sedan", category: "Car" },
  { name: "Toyota New Vios Silver", plateNumber: "จง 2967", type: "Sedan", category: "Car" },
  { name: "Toyota New Vios Silver", plateNumber: "จง 2756", type: "Sedan", category: "Car" },
  { name: "Toyota New Vios White", plateNumber: "ขว 9050", type: "Sedan", category: "Car" },
  { name: "Toyota New Vios Silver", plateNumber: "จต 6733", type: "Sedan", category: "Car" },
  { name: "Toyota New Yaris Ative 2018 Blue", plateNumber: "งบ 7141", type: "Economy", category: "Car" },
  { name: "Toyota New Yaris Ative 2019 White", plateNumber: "งพ 1849", type: "Economy", category: "Car" },
  { name: "Toyota New Yaris Ative 2022 White", plateNumber: "จง 9211", type: "Economy", category: "Car" },
  { name: "Toyota New Yaris Ative 2022 White", plateNumber: "จง 9216", type: "Economy", category: "Car" },
  { name: "Toyota New Yaris Ative 2022 White", plateNumber: "จง 9214", type: "Economy", category: "Car" },
  { name: "Toyota New Yaris Ative 2022 White", plateNumber: "งจ 9213", type: "Economy", category: "Car" },
  { name: "Toyota New Yaris Ative 2022 White", plateNumber: "จง 9215", type: "Economy", category: "Car" },
  { name: "Toyota New Yaris Ative 2022 White", plateNumber: "จง 9212", type: "Economy", category: "Car" },
  { name: "Toyota New Yaris Ative 2022 White", plateNumber: "จง 9218", type: "Economy", category: "Car" },
  { name: "Toyota New Yaris Ative 2022 White", plateNumber: "จง 9217", type: "Economy", category: "Car" },
  { name: "Toyota New Yaris Ative 2022 Silver", plateNumber: "จจ 9793", type: "Economy", category: "Car" },
  { name: "Toyota New Yaris Ative 2019 Black", plateNumber: "2ฑฒ 3163", type: "Economy", category: "Car" },
  { name: "Toyota New Yaris Ative 2022 White", plateNumber: "จต 4010", type: "Economy", category: "Car" },
  { name: "Toyota New Yaris Ativ 2022 White", plateNumber: "จต 4011", type: "Economy", category: "Car" },
  { name: "Toyota New Yaris Ativ 2023 White", plateNumber: "จธ 7265", type: "Economy", category: "Car" },
  { name: "Toyota New Yaris Ativ 2023 White", plateNumber: "จธ 7266", type: "Economy", category: "Car" },
  { name: "Toyota New Yaris Ativ 2023 White", plateNumber: "จธ 8263", type: "Economy", category: "Car" },
  { name: "Toyota New Yaris Ativ 2023 White", plateNumber: "จ ธ 8261", type: "Economy", category: "Car" },
  { name: "Toyota New Yaris Ativ 2023 White", plateNumber: "จ ธ 8264", type: "Economy", category: "Car" },
  { name: "Toyota New Yaris Ativ 2023 White", plateNumber: "จธ 8262", type: "Economy", category: "Car" },
  { name: "Toyota New Yaris Ativ 2023 White", plateNumber: "จว 3412", type: "Economy", category: "Car" },
  { name: "Toyota New Yaris Ativ 2023 White", plateNumber: "จว 3413", type: "Economy", category: "Car" },
  { name: "Toyota New Yaris Ativ 2023 White", plateNumber: "จว 3411", type: "Economy", category: "Car" },
  { name: "Toyota New Yaris Ativ 2024 White", plateNumber: "จว 3414", type: "Economy", category: "Car" },
  { name: "Toyota Yaris Ativ 2026 CVT 1.2 SMART White", plateNumber: "ข-0321", type: "Economy", category: "Car" },
  { name: "Toyota Yaris Ativ 2026 CVT 1.2 SMART White", plateNumber: "ข-0338", type: "Economy", category: "Car" },
  { name: "Toyota Yaris Ativ 2026 CVT 1.2 SMART White", plateNumber: "ข-0417", type: "Economy", category: "Car" },
  { name: "Toyota Yaris Ativ 2026 CVT 1.2 SMART White", plateNumber: "ข-0400", type: "Economy", category: "Car" },
  { name: "Toyota Yaris Ativ 2026 CVT 1.2 SMART White", plateNumber: "ก-5324", type: "Economy", category: "Car" },
  { name: "Toyota New Yaris White", plateNumber: "ขพ 3507", type: "Economy", category: "Car" },
  { name: "Toyota Yaris Hatchback 2020", plateNumber: "จธ 3264", type: "Economy", category: "Car" },
  { name: "Nissan Navara Silver", plateNumber: "ขอ 4826", type: "Truck", category: "Car" },
  { name: "Toyota Revo Vigo White", plateNumber: "งค 8242", type: "Truck", category: "Car" },
  { name: "Toyota Revo Vigo White", plateNumber: "งค 8230", type: "Truck", category: "Car" },
  { name: "Toyota Revo Vigo White", plateNumber: "จจ 9801", type: "Truck", category: "Car" },
  { name: "Toyota Revo Vigo White", plateNumber: "จจ 9802", type: "Truck", category: "Car" },
  { name: "Toyota Revo Vigo White", plateNumber: "จจ 9803", type: "Truck", category: "Car" },
  { name: "Toyota Revo Vigo White", plateNumber: "จจ 9794", type: "Truck", category: "Car" },
  { name: "Toyota Revo Vigo White", plateNumber: "จฉ 3671", type: "Truck", category: "Car" },
  { name: "Toyota Revo Vigo White", plateNumber: "จฉ 3672", type: "Truck", category: "Car" },
  { name: "Toyota Revo Vigo White", plateNumber: "จฉ 7141", type: "Truck", category: "Car" },
  { name: "Toyota Revo Vigo White", plateNumber: "จฉ 8462", type: "Truck", category: "Car" },
  { name: "Toyota Revo Vigo White", plateNumber: "จฉ 8461", type: "Truck", category: "Car" },
  { name: "Toyota Revo Vigo Silver", plateNumber: "จฉ 9531", type: "Truck", category: "Car" },
  { name: "Toyota Revo Vigo Silver", plateNumber: "จต 4012", type: "Truck", category: "Car" },
  { name: "Toyota Revo Vigo Black", plateNumber: "7001", type: "Truck", category: "Car" },
  { name: "Toyota Revo Vigo Black", plateNumber: "จท 4743", type: "Truck", category: "Car" },
  { name: "Toyota Revo Vigo Black", plateNumber: "จร 6786", type: "Truck", category: "Car" },
  { name: "Toyota Revo Vigo 2022 White", plateNumber: "จต 4013", type: "Truck", category: "Car" },
  { name: "Toyota Revo Vigo 2024 White", plateNumber: "จร 7734", type: "Truck", category: "Car" },
  { name: "Toyota Revo Vigo 2024 White", plateNumber: "จร 7735", type: "Truck", category: "Car" },
  { name: "Toyota Revo Vigo 2024 White", plateNumber: "จร 7739", type: "Truck", category: "Car" },
  { name: "Toyota Revo Vigo 2024 White", plateNumber: "จร 7740", type: "Truck", category: "Car" },
  { name: "MG Extender 2021", plateNumber: "จฉ 4194", type: "Truck", category: "Car" },
  { name: "Honda City Grey", plateNumber: "งธ 4520", type: "Sedan", category: "Car" },
  { name: "Honda City White", plateNumber: "จต 4836", type: "Sedan", category: "Car" },
  { name: "Honda City White", plateNumber: "งค 9502", type: "Sedan", category: "Car" },
  { name: "Honda Jazz White", plateNumber: "ขร 3882", type: "Economy", category: "Car" },
  { name: "Toyota Fortuner White", plateNumber: "ขย 47", type: "SUV", category: "Car" },
  { name: "Toyota Fortuner White", plateNumber: "ขน 1577", type: "SUV", category: "Car" },
  { name: "Toyota Fortuner Blue", plateNumber: "งจ 3720", type: "SUV", category: "Car" },
  { name: "Toyota Fortuner White", plateNumber: "จง 1248", type: "SUV", category: "Car" },
  { name: "Toyota Fortuner White", plateNumber: "งจ 7107", type: "SUV", category: "Car" },
  { name: "Toyota Fortuner White", plateNumber: "ขพ 8015", type: "SUV", category: "Car" },
  { name: "Toyota Fortuner White", plateNumber: "จธ 7261", type: "SUV", category: "Car" },
  { name: "Toyota Fortuner White", plateNumber: "จธ 7262", type: "SUV", category: "Car" },
  { name: "Toyota Fortuner White", plateNumber: "จธ 7263", type: "SUV", category: "Car" },
  { name: "Toyota Fortuner White", plateNumber: "จธ 7264", type: "SUV", category: "Car" },
  { name: "Toyota Fortuner White", plateNumber: "จร 7737", type: "SUV", category: "Car" },
  { name: "Toyota Fortuner White", plateNumber: "จร 7736", type: "SUV", category: "Car" },
  { name: "Toyota Fortuner White", plateNumber: "จธ 7738", type: "SUV", category: "Car" },
  { name: "Toyota Fortuner White", plateNumber: "จธ 7741", type: "SUV", category: "Car" },
  { name: "Ford Everest", plateNumber: "จธ 2171", type: "SUV", category: "Car" },
  { name: "Ford Everest", plateNumber: "จธ 2172", type: "SUV", category: "Car" },
  { name: "Ford Everest", plateNumber: "จธ 2173", type: "SUV", category: "Car" },
  { name: "Ford Everest", plateNumber: "จธ 2174", type: "SUV", category: "Car" },
];

export const SEED_WEBSITE_CARS = [
  {
    name: "Toyota Vios",
    make: "Toyota",
    model: "Vios",
    yearRange: "model 2018 - 2021",
    pricePerDay: 1350,
    priceMonthly: 6950,
    engineSize: "1.5",
    fuelType: "Petrol",
    transmission: "Auto",
    passengers: 5,
    airCon: true,
    audio: "CD/USB/AUX",
    displayOrder: 1,
    isActive: true,
    mainImage: "https://firebasestorage.googleapis.com/v0/b/pattaya-rent-a-car-rebuild.firebasestorage.app/o/Toyota_Vios.avif?alt=media&token=0fe7fe5f-bba1-4013-bec6-b5983d06e63d",
    shadowImage: "",
    realImages: [
      "https://firebasestorage.googleapis.com/v0/b/pattaya-rent-a-car-rebuild.firebasestorage.app/o/Toyota_Vios.avif?alt=media&token=0fe7fe5f-bba1-4013-bec6-b5983d06e63d"
    ],
    priceGridVehicle: "Vios"
  },
  {
    name: "Toyota Yaris Ativ Sport",
    yearRange: "model 2023 - 2026",
    pricePerDay: 1300,
    priceMonthly: 6300,
    engineSize: "1.2",
    fuelType: "Petrol",
    transmission: "Auto",
    passengers: 5,
    airCon: true,
    audio: "CD/USB/AUX",
    displayOrder: 3,
    isActive: true,
    mainImage: "https://firebasestorage.googleapis.com/v0/b/pattaya-rent-a-car-rebuild.firebasestorage.app/o/Toyota_Ativ_new.avif?alt=media&token=69656f82-c64e-474b-8103-d58536633d57",
    shadowImage: "",
    realImages: [],
    priceGridVehicle: "Ativ Sport"
  },
  {
    name: "Honda City",
    yearRange: "model 2018 - 2019",
    pricePerDay: 1450,
    priceMonthly: 7350,
    engineSize: "1.5",
    fuelType: "Petrol",
    transmission: "Auto",
    passengers: 5,
    airCon: true,
    audio: "CD/USB/AUX",
    displayOrder: 4,
    isActive: false,
    mainImage: "",
    shadowImage: "",
    realImages: [],
    priceGridVehicle: "City"
  },
  {
    name: "Nissan Navara",
    yearRange: "model 2016 - 2018",
    pricePerDay: 1600,
    priceMonthly: 8400,
    engineSize: "2.4",
    fuelType: "Diesel",
    transmission: "Auto",
    passengers: 5,
    airCon: true,
    audio: "CD/USB/AUX",
    displayOrder: 7,
    isActive: false,
    mainImage: "",
    shadowImage: "",
    realImages: [],
    priceGridVehicle: "Navara"
  },
  {
    name: "Toyota Fortuner (Old Model)",
    yearRange: "model 2015 - 2018",
    pricePerDay: 1800,
    priceMonthly: 9800,
    engineSize: "3",
    fuelType: "Diesel",
    transmission: "Auto",
    passengers: 7,
    airCon: true,
    audio: "CD/USB/AUX",
    displayOrder: 8,
    isActive: true,
    mainImage: "https://firebasestorage.googleapis.com/v0/b/pattaya-rent-a-car-rebuild.firebasestorage.app/o/Toyota_Fortuner_Old.png?alt=media&token=0b72046f-a429-440b-8646-2f54d60df87f",
    shadowImage: "",
    realImages: [],
    priceGridVehicle: "Old Fortuner"
  },
  {
    name: "New Toyota Fortuner",
    yearRange: "model 2023 - 2024",
    pricePerDay: 2200,
    priceMonthly: 12600,
    engineSize: "2.4",
    fuelType: "Diesel",
    transmission: "Auto",
    passengers: 7,
    airCon: true,
    audio: "CD/USB/AUX",
    displayOrder: 10,
    isActive: true,
    mainImage: "https://firebasestorage.googleapis.com/v0/b/pattaya-rent-a-car-rebuild.firebasestorage.app/o/Toyota_Fortuner_New.avif?alt=media&token=66f98b14-11b3-4776-9278-ae387accc951",
    shadowImage: "",
    realImages: [],
    priceGridVehicle: "New Fortuner"
  },
  {
    name: "Toyota Yaris Ativ",
    yearRange: "model 2019 - 2022",
    pricePerDay: 1450,
    priceMonthly: 7350,
    engineSize: "1.2",
    fuelType: "Petrol",
    transmission: "Auto",
    passengers: 5,
    airCon: true,
    audio: "CD/USB/AUX",
    displayOrder: 2,
    isActive: true,
    mainImage: "https://firebasestorage.googleapis.com/v0/b/pattaya-rent-a-car-rebuild.firebasestorage.app/o/Toyota_Yaris.avif?alt=media&token=37eb78d6-cf9e-4886-9c5d-a45e00426722",
    realImages: [],
    priceGridVehicle: "Ativ"
  },
  {
    name: "Toyota Vios CVT",
    yearRange: "model 2021",
    pricePerDay: 1500,
    priceMonthly: 7700,
    engineSize: "1.5",
    fuelType: "Petrol",
    transmission: "Auto",
    passengers: 5,
    airCon: true,
    audio: "CD/USB/AUX",
    displayOrder: 6,
    isActive: false,
    mainImage: "https://firebasestorage.googleapis.com/v0/b/pattaya-rent-a-car-rebuild.firebasestorage.app/o/Toyota_Vios.avif?alt=media&token=0fe7fe5f-bba1-4013-bec6-b5983d06e63d",
    shadowImage: "",
    realImages: [],
    priceGridVehicle: "Vios CVT"
  },
  {
    name: "Toyota Revo",
    yearRange: "Model 2022 - 2024",
    pricePerDay: 1800,
    priceMonthly: 9800,
    engineSize: "2.4",
    fuelType: "Diesel",
    transmission: "Auto",
    passengers: 5,
    airCon: true,
    audio: "CD/USB/AUX",
    displayOrder: 7,
    isActive: true,
    mainImage: "https://firebasestorage.googleapis.com/v0/b/pattaya-rent-a-car-rebuild.firebasestorage.app/o/Toyota_Revo.avif?alt=media&token=7e7510af-c30e-4c30-9bf8-aef7109dc5f5",
    shadowImage: "",
    realImages: [],
    priceGridVehicle: "Revo"
  },
  {
    name: "MG Extender",
    yearRange: "model 2019 - 2021",
    pricePerDay: 1700,
    priceMonthly: 9100,
    engineSize: "2",
    fuelType: "Diesel",
    transmission: "Auto",
    passengers: 5,
    airCon: true,
    audio: "CD/USB/AUX",
    displayOrder: 6,
    isActive: true,
    mainImage: "",
    shadowImage: "",
    realImages: [],
    priceGridVehicle: "Extender"
  },
  {
    name: "Next Gen Ford Everest",
    yearRange: "model 2023",
    pricePerDay: 0,
    priceMonthly: 0,
    engineSize: "2",
    fuelType: "Diesel",
    transmission: "Auto",
    passengers: 7,
    airCon: true,
    audio: "CD/USB/AUX",
    displayOrder: 11,
    isActive: true,
    mainImage: "",
    shadowImage: "",
    realImages: [],
    priceGridVehicle: "Everest"
  },
  {
    name: "Toyota Veloz Premium",
    yearRange: "2026",
    pricePerDay: 0,
    priceMonthly: 0,
    engineSize: "1.5",
    fuelType: "Petrol",
    transmission: "Auto",
    passengers: 7,
    airCon: true,
    audio: "USB/Bluetooth",
    displayOrder: 4,
    isActive: true,
    mainImage: "https://firebasestorage.googleapis.com/v0/b/pattaya-rent-a-car-rebuild.firebasestorage.app/o/Toyota_Veloz.avif?alt=media&token=93adca99-cdcd-49e1-9b0e-977cd678c0a4",
    shadowImage: "",
    realImages: [],
    priceGridVehicle: "Veloz"
  }
];
